#!/usr/bin/env python
# -*- encoding=utf8 -*-
## Lazy Script Manage Commander
#
# Lazyscript system command-line management program.
#
from os import system
import sys

try:
	cmder=sys.argv[1]
	if 'repo' == cmder.strip():
		from lazyscript.repo import sign_repopath
		action=sys.argv[2]
		if 'sign' == action:
			origin_path=sys.argv[3]
			print sign_repopath(origin_path, sys.argv[4])
	elif 'gui' == cmder:
		print cmder
		from ui import GUI
		GUI().start()
except KeyError:#IndexError:
	print 'see more information in this file content.'
