#!/usr/bin/env python
# -*- encoding=utf8 -*-
## Lazy Script Manage Commander
#
# Lazyscript system command-line management program.
#
from os import system
import sys

from lazyscripts.util.detect import run_asroot

if not run_asroot():
    print "please run as root or use slzs command to launch."
    sys.exit()

try:
	cmder=sys.argv[1]
	if 'repo' == cmder.strip():
		from lazyscripts.repo import sign_repopath
		action=sys.argv[2]
		if 'sign' == action:
			origin_path=sys.argv[3]
			#print sign_repopath(origin_path, sys.argv[4])
			print sign_repopath(origin_path)
	elif 'gui' == cmder:
		from ui import GUI
		GUI().start()
except IndexError:
	print 'see more information in this file content.'
