#!/bin/bash
# @author '2009 Hsin Yi Chen (陳信屹) <ossug.hychen@gmail.com>'

# run Lazyscripts with root access
gksudo --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env ./lzs $@
